### ISSUE TITLE
Error in question text

### ISSUE THREAD

**Issue by mhebing** [paneldata/metadata#12]
https://paneldata.org/questions/47638

**Comment by kwenzig** [comment]
The metadata in the gitlab repository (http://gitlab.soep.de/mhebing/soep-core-import.git) are correct. The german instruction text and the item battery seem to belong to a previous version of this questionnaire, which has not been deleted.

**Comment by kwenzig** [comment]
Ich kehre zurück am 24.08.2015.

Dann werde ich mich um das Anliegen kümmern.
Beste Grüße
Knut Wenzig


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[metadata] Error in question text (#12)" gesendet am 08/14/2015 13:41:30.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.
