### ISSUE TITLE
2012 metadata for soep-core

### ISSUE THREAD

**Issue by mhebing** [paneldata/metadata#13]

**Comment by kwenzig** [comment]
Ich kehre zurück am 24.08.2015.

Dann werde ich mich um das Anliegen kümmern.
Beste Grüße
Knut Wenzig


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "[metadata]
2012 metadata for soep-core (#13)" gesendet am 08/14/2015 13:39:22.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by afuetterer** [comment]
@kwenzig: Can this be closed?
