### ISSUE TITLE
Run r2ddi.

### ISSUE THREAD

**Issue by mhebing** [paneldata/metadata#4]
- [ ] SOEP-Core v29
- [x] SOEP-Core v30
- [ ] SOEPlong
- [ ] ARD
- [x] Pairfam
- [ ] SOEP-IS ?

**Comment by mhebing** [comment]
@kwenzig Are the SOEP-IS xmls up to date?

**Comment by kwenzig** [comment]
When did you update them?

**Comment by mhebing** [comment]
I referred to the one in the metadata-repository for SOEP-IS. Are they up to date or should we run r2ddi on the latest version of the datasets?

**Comment by kwenzig** [comment]
Ich kehre zurück am 24.08.2015.

Dann werde ich mich um das Anliegen kümmern.
Beste Grüße
Knut Wenzig


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[metadata] Run r2ddi. (#4)" gesendet am 08/14/2015 13:40:15.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.
